// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWiQTqk9y0v3YCJ-gjC8CrcFaZbfYgFe0',
    appId: '1:877065628249:web:ca4d24539aed9284ff9f48',
    messagingSenderId: '877065628249',
    projectId: 'a-la-care-b2664',
    authDomain: 'a-la-care-b2664.firebaseapp.com',
    storageBucket: 'a-la-care-b2664.appspot.com',
    measurementId: 'G-9PZ83QKQ2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHjLvp_IJD3vqcMEZT26HZ-kiJCIeSk40',
    appId: '1:877065628249:android:57dbc536d9c4a55cff9f48',
    messagingSenderId: '877065628249',
    projectId: 'a-la-care-b2664',
    storageBucket: 'a-la-care-b2664.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjNW8h3w9CMe0cZeJA1noOHnNwqCZiWR0',
    appId: '1:877065628249:ios:9480e3c20bf8b410ff9f48',
    messagingSenderId: '877065628249',
    projectId: 'a-la-care-b2664',
    storageBucket: 'a-la-care-b2664.appspot.com',
    iosBundleId: 'com.example.aLaCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjNW8h3w9CMe0cZeJA1noOHnNwqCZiWR0',
    appId: '1:877065628249:ios:9480e3c20bf8b410ff9f48',
    messagingSenderId: '877065628249',
    projectId: 'a-la-care-b2664',
    storageBucket: 'a-la-care-b2664.appspot.com',
    iosBundleId: 'com.example.aLaCare',
  );
}
